### ISSUE TITLE
Cannot get it to render at all

### ISSUE THREAD

**Issue by ettiennelouw** [mjanssen/Laravel-5-breadcrumbs-bundle#13]
Trying to this to my site with the global option.

Project 1:
Error (Laravel 5.2):
ErrorException in Breadcrumbs.php line 102:
Undefined index: except 

Project 2:
Error:(Almost clean laravel project 5.2):
ErrorException in Breadcrumbs.php line 102:
in_array() expects parameter 2 to be array, null given

**Comment by mjanssen** [comment]
Hi Etiennelouw,

Did you import the config in your application? The provided `config_file_breadcrumbs.php` should be stored within the folder /config under the name `breadcrumbs.php`. This should fix the undefined index except error. Let me know if this also fixes the error in project 2.

**Comment by ettiennelouw** [comment]
Dude.. Im so sorry for wasting your time. That worked 100% Thanks

**Comment by mjanssen** [comment]
No problem, no time was wasted ;)

**Comment by mjanssen** [comment]
If you update the package, you can remove id's from the breadcrumbs (by putting "numbers*" in the except array). Also an option to remove ".html" from breacrumb names is implemented (if you need it).

**Comment by ettiennelouw** [comment]
Brilliant, I have updated the package now and added the new breadcrumbs.php file im getting:
ErrorException in daee8952aec588a4678e8a9bc0755c075eacd417.php line 118:
Trying to get property of non-object (View:

**Comment by ettiennelouw** [comment]
Awsome everything is working 100% Just has to clear cache and all is good thanks alot for your code addition.
