### ISSUE TITLE
Fatal error : Class 'Breadcrumbs' not found on view

### ISSUE THREAD

**Issue by sachinvrg** [mjanssen/Laravel-5-breadcrumbs-bundle#6]
Hello,

I have setup all the stuffs you mentioned here, but when I call breadcrumbs on view, it is giving fatal error  Class 'Breadcrumbs' not found.

can you please help me, I am using laravel 5.1

**Comment by mjanssen** [comment]
Let me look into it :)

**Comment by mjanssen** [comment]
I'll look into it :)

**Comment by sachinvrg** [comment]
Thank you for consider my issue,
may be you want to have a look at my controller, here it is 
<?php namespace App\Modules\Admin\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use mjanssen\BreadcrumbsBundle\Breadcrumbs;
use  Session,Auth,Redirect,Lang,Config,App;

class AdminController extends Controller {

```
public function __construct()
{
    if(!(Auth::user()))
    {
        Redirect::to('login')->send();
    }
}

/**
 * Display a listing of the resource.
 *
 * @return Response
 */
public function index()
{
    Breadcrumbs::addBreadcrumb('Dashboard', '/admin');
    Breadcrumbs::addBreadcrumb('Second crumb', '/second-page');


    return view("admin::index");
}


public function logout()
{
    Auth::logout();
    return redirect('login');
} 
```

}

**Comment by sachinvrg** [comment]
on my view I have this - {{ Breadcrumbs::generate() }}

**Comment by mjanssen** [comment]
Ahh, consider pushing your data from the controller to the view.

That would be

```
$data = [
    'breadcrumbs' => Breadcrumbs::generate()
]

return view("admin::index", $data);

//Your view
{{ $breadcrumbs }} // Is an ol tag including your breadcrumbs
```

By default the view should only be used for displaying breadcrumbs and not generating them (logic should be handled in your controller).

Let me know if it works out like this :)

**Comment by sachinvrg** [comment]
Hello mjanssen,
your following code was giving syntax error - 
$data = [
    'breadcrumbs' => Breadcrumbs::generate()
]
then I change it to - $data['breadcrumbs'] = Breadcrumbs::generate();

and return  view("admin::index",$data);

but on my view it is showing complete HTML in place of breadcrumb - please check attached screen shot.
![breadcrumb](https://cloud.githubusercontent.com/assets/12329845/9974741/1128604a-5ebd-11e5-8e11-936ce51b1a71.png)

**Comment by mjanssen** [comment]
Whoops! Try {!! $breadcrumbs !!} in your view, that should do the trick. Laravel escapes HTML code while using {{}} vars.

**Comment by sachinvrg** [comment]
Thank you very much mjanssen, 
now it is showing breadcrumbs, but not properly formated, I think there must be some class for it, 
if you know then please let me know class name and how can I set it?
Thanks again.
![breadcumb-format](https://cloud.githubusercontent.com/assets/12329845/9975576/17f6102c-5ede-11e5-9541-303df688499e.png)

**Comment by mjanssen** [comment]
I suppose you added the config file (config/breadcrumbs.php (https://github.com/mjanssen/Laravel-5-breadcrumbs-bundle/blob/master/config_file_breadcrumbs.php for an example)).

In this file you can set the class which is used by the <ol> tag. By default it uses bootstrap CSS classes, which can be altered to your own wishes.

Let me know if this works for you :)

**Comment by sachinvrg** [comment]
Thank you very much man, you are genius :+1:  
I didn't find  breadcrumbs.php file in my config directory but I added 'breadcrumb' class directly to ol tag, and it is looking nice :)
